apiVersion: v1
kind: Namespace
metadata:
  name: simplecni
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplecni
  namespace: simplecni
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplecni
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames: [ "kubeadm-config" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simplecni
subjects:
  - kind: ServiceAccount
    name: simplecni
    namespace: simplecni
roleRef:
  kind: ClusterRole
  name: simplecni
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simplecni
  namespace: simplecni
  labels:
    app: simplecni
spec:
  selector:
    matchLabels:
      app: simplecni
  template:
    metadata:
      labels:
        app: simplecni
    spec:
      volumes:
        - name: cni-config
          hostPath:
            path: /etc/cni/net.d
            type: DirectoryOrCreate
      containers:
        - name: shiba
          image: cox96de/simplecni:latest
          imagePullPolicy: Always

          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-config
              mountPath: /etc/cni/net.d
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
      serviceAccountName: simplecni
      tolerations:
        - operator: Exists
